---
name: smart-compact
description: Instructions for tree-shaking a user-provided AI session transcript
disable-model-invocation: true
---
This Skill's purpose is to compact an AI session transcription by removing redundant-information messages and keeping the contentful ones intact.

### 1. Skip Trial-and-Error Bouts (All Tools)
**Drop the struggle; keep the resolution.**
-   Identify sequences of thrashing-whether it's fighting syntax errors, correcting failed attempts, or guessing paths. Discard the entire iterative loop of failures and keep only the final, successful tool invocation that resolves the bout. Preserve its resolution; represent it under the tool-call rules below.
-   Drop external technical difficulties like user interrupts, connection retries, etc.

### 2. Remove "murmur" and general noise
- **Drop "murmur"**: Isolated messages like "Good, that worked.", "File has been created/updated successfully", or "Now I'll do this or that: ..."
- **Drop tool messages merely confirming success**: "Action X was successful" or "Tool completed with no output." Also drop Todo updates/writes. These messages don't hold real content, reading more like the assistant murmuring under its breath.
- Note that these can show up in user messages as well as assistant messages.
- Drop "User commands" with no semantic importance.
<EXAMPLES-OF-USER-COMMANDS-WITH-NO-SEMANTIC-IMPORTANCE handle=discard rationale="These are mere technicalities, and don't hold any story.">
    <local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>
    ## User Command Input
    ```yaml
    name: "/effort"
      message: "effort"
      args: "medium"
    ```
    ## User Command Output
    Set effort level to medium: Balanced approach with standard implementation and testing
    [Request interrupted by user]
</EXAMPLES-OF-USER-COMMANDS-WITH-NO-SEMANTIC-IMPORTANCE handle=discard rationale="These are mere technicalities, and don't hold any story.">

<EXAMPLES-OF-USER-COMMANDS-WITH-SEMANTIC-IMPORTANCE handle=keep rationale="The user has commanded the assistant to use a tool (a Skill), which triggered context gathering; and context is story.">
    ## User Command Input
    ```yaml
    message: "catchup"
    name: "/catchup"
    args: "on thoughts/26-04-07-context-menu-research/, we are going to implement the plans/1-...plan.md plan. it's a client side effort. but before you make any changes, read everything relevant based on the docs as well as your greps, then tell me when you are ready."
    ```
    </user-command-input>
</EXAMPLES-OF-USER-COMMANDS-WITH-SEMANTIC-IMPORTANCE handle=keep rationale="The user has commanded the assistant to use a tool (a Skill), which triggered context gathering; and context is story.">

### 3. File references only
**Keep only the tool-input reference of each operation that CRUD's a file.**
Drop the tool call payload (old/new text, file content) and the tool's output data.

For structured JSON transcripts, this means reducing the tool-input block to a minimal path reference.
In XML-like pseudocode:
```
<Edit path="...">
Old: ...
New: ...
</Edit>
```
Should become only:
```
<Edit path="..."/>
```
In JSON:
```json
{"type": "tool-input", "name": "Read", "path": "/path/to/file.py", ...}
```
→ `"<Read path=\"/path/to/file.py\" id=\"...\"/>"`

This applies to `Read`, `read_many_files`, `Edit`, `Write`, `Patch`, and `Delete`. A multi-file read becomes one `<Read …/>` per path. For Bash, use the boundary below rather than treating every incidental file touch as CRUD.

**Bash boundary**: pure mechanical setup/teardown (`mkdir`, `kill`, `sleep`) or simple `ls` inventory calls can be reduced to a path-only invocation. A Bash command that *discovers information* a next step depends on or *validates* completion may instead qualify as a pivotal tool skeleton below.

### 4. Pivotal non-CRUD tools become semantic skeletons

**Keep the decision, not the transcript.** When a non-CRUD tool call materially changes the assistant's decision, execution path, or established system state, replace its raw input and output with one self-contained XML skeleton:

```xml
<tool-skeleton name="Bash" command="…" purpose="…" outcome="…" meaning="…"/>
```

1. `name`, `command`, `purpose`, and `outcome` are required. `meaning` is required when the result explains a consequential decision; otherwise omit it.
2. `command` is a concise, faithful description of the executed command. Keep the exact command only when its precise syntax is itself material to the story.
3. `purpose` states what the tool was meant to establish or do. `outcome` records the decisive result, including definitive validation evidence. `meaning` connects that result to the decision or state transition it enabled.
4. This replaces the raw tool payload and output. Do not duplicate their details in surrounding narration unless the conversation itself needs them.
5. File CRUD still wins: represent `Read`, `read_many_files`, `Edit`, `Write`, `Patch`, `Delete`, and purely mechanical file-touching commands only as the path references required by §3. Omit non-pivotal tools entirely.

For example:

```xml
<tool-skeleton name="Bash" command="pytest" purpose="Validate the fix" outcome="148 tests passed" meaning="Proved the change before release"/>
```

### 5. End the compacted result with a list of affected file references
At the very end, create such an object:
```
<affected-files>
- @path/to/file1.ext
- @...
</affected-files>
```
The unique set of all CRUD'ed files in the session.

### 6. The "Final Observation" Rule (`Read`, `Bash` Exploration)
**Keep only the tool call that successfully acquires the target information.**
- **Scratchpads**: Drop reads, writes and edits of transient/debug/temporary files created by the agent during the session with the purpose of helping itself arrive at some desired state.
- **Bash:** Group commands by semantic purpose. Keep only the final call that effectively returns the answer; represent it as a pivotal skeleton when it changed the story, otherwise drop it.

### 7. The "Definitive Validation" Rule (`Bash` Execution)
**Keep the proof, drop the debugging loop.** For commands that validate system state (e.g., running `pytest` or a build script), keep only the final successful execution. Record its decisive evidence in the skeleton's `outcome` attribute when it is pivotal.

---

**Export and round-trip with `ch`** when the source is a supported AI CLI session:
```bash
ch <session-id> -t:s -f json > transcription.json
ch <session-id> -t:s > transcription.md
```
Treat the structured JSON as the source of truth. Convert in either direction with:
```bash
ch parse transcription.json > transcription.md
ch parse -f json transcription.md > transcription.json
```
`ch parse` accepts compacted messages containing multiple string content blocks. A Markdown round trip canonicalizes adjacent text blocks and timestamp precision, so do not expect byte-identical JSON; rerendered Markdown is the stable representation.

**Always make a backup before editing the transcript in-place**:
```bash
cp transcription.json transcription.backup.json
```
File-mutation scripts use index-based logic. Re-running on already-compacted output
with stale indices will corrupt the result. Work from the backup if you need to restart.
Always reference messages by their stable `original_index` field, not by positional
array offset — the offset shifts with every removal. Work only on exported transcription
files; do not modify the native CLI agent's `.jsonl` session files.

**Exception — resumable native compaction.** When the user explicitly asks to compact
the native session `.jsonl` itself so the compacted session stays resumable, operate on
a NEW copy with a new session id (never the original file) and first read
`references/native-pi-session.md` — it defines the file anatomy, the five resumability
invariants (single root, active-path-only, re-chaining, tool pairing closure, header
identity), which compaction rules map to which native structures, and the
`scripts/compact_native_pi_session.py` one-command tool (accepts a session id or path,
bootstraps a new resumable copy, transforms, and verifies — including loading through
pi's own session-manager code). Run it; don't rewrite it.

**Deterministic pre-processing** (no semantics, no heuristics):
```bash
uv run python3 scripts/prune_transcript.py transcription.json > pruned.json
```
Removes todos and raw outputs for Read/read_many_files/Write/Edit/Patch/Delete,
expands multi-file reads, and replaces file inputs in place without reordering mixed blocks.

**Diagnostics**:
```bash
uv run -p python3 --with=pyyaml python3 scripts/analyze_transcript_json.py transcription.json
```
Provides structured data about the transcript (tool-output indices, repeated file touches,
validation runs, duplicate commands) to inform semantic decisions. Use its output as
a maybe-worth-checking guide, not authoritative. Read the transcription in full regardless.

**Author semantic decisions only** — every mechanical field is derived for you. Write a
decisions file containing nothing but judgments:
```json
{
  "drop_texts": [90, 262],
  "drop_text_blocks": [{"original_index": 12, "contains": "Now I'll wrap up"}],
  "skeletons": [
    {"original_index": 236, "command": "…", "purpose": "…", "outcome": "…", "meaning": "…"}
  ],
  "scratchpad_paths": ["/tmp/render_helper.py"],
  "opaque_artifacts": ["/path/created/by/opaque/shell.csv"]
}
```
Semantics: every surviving raw tool block is inferred noise and dropped unless a skeleton
preserves its meaning. `drop_texts` removes whole contentful messages. `drop_text_blocks`
removes individual prose blocks inside mixed messages by substring; prose in mixed messages
is otherwise preserved while their tool blocks are removed. A skeleton anchors to its
message's single tool-input block; when a message holds several, add `"tool_id"` to select
one (multiple skeletons per message are allowed). The skeleton's `name` is derived from the
anchored block — override it only when the skeleton summarizes a wider bout.
`scratchpad_paths` excludes transient helper files from both the transcript and the footer.
`opaque_artifacts` is the narrow escape hatch for shell-created files no structured tool
reported. Ordinarily only `drop_texts` and `skeletons` are needed.
```bash
uv run python3 scripts/generate_compaction_plan.py pruned.json decisions.json > compaction-plan.json
uv run -p python3 python3 scripts/apply_compaction_plan.py pruned.json compaction-plan.json > compacted.json
```
The generator computes the source checksum, infers the raw-tool drop set, serializes and
XML-escapes skeletons, derives every expected tool ID, honors `remove: true` marks as drops,
and collects affected-file provenance automatically: file references, registered
artifact-producing tools (e.g. Lumen output paths), and declared opaque artifacts. It prints
a mandatory audit to stderr — inferred removals grouped by tool, normalized mixed messages,
skeleton anchors, explicit drops, scratchpad exclusions, affected paths with provenance
category, final counts — and self-verifies the plan against the apply stage before emitting
it. Unresolved structured blocks, invalid or ambiguous anchors, conflicting decisions,
unreferenced scratchpad paths, and artifact-extractor failures fail loudly.

The generated plan is a plain, inspectable JSON artifact (`drop_messages`,
`replace_messages` with `expected_tool_ids`, `affected_files_extra`, `source_sha256`).
The apply stage retains its own validation: stale checksums, missing indices, mismatched
tool IDs, surviving raw blocks, and duplicate footers are refused.
When a Markdown transcription accompanies the JSON, regenerate it directly from the final compacted JSON:
```bash
ch parse compacted.json > compacted.md
```
Do not hand-render Markdown or write an ad hoc converter.

**Non-destructive marking** while reviewing exported JSON: flag an object for removal with
`remove: true`, guarded by stable index plus content:
```bash
scripts/markremove.py transcription.json --original-index <original_index> \
  --safeguard='<short substring of that object content>'
```
The mark is written only when that exact `original_index` contains the safeguard substring.

**Quick story-first orientation** (optional): read the session as simplified Markdown
without tool calls to understand the narrative arc before diving into details:
```sh
jq -r '
     .[]
     | if .content[0] | type == "string" then
         "## \(if .role == "user" then "User" else "Assistant" end)\n\n" + .content[0] + "\n"
       else
         "## Tool\n\n" + (
           if .content[0].type == "tool-input" then
             "```bash [input]\n" + (.content[0].command // "") + "\n```"
           else
             "```[output]\n" + ([.content[0].content[] | select(.type == "text") | .text] | join("")) + "\n```"
           end
         ) + "\n"
       end
   ' transcription.json
```

---

## Useful Techniques

### For structural inspection

**Flat message inventory** — scan all messages by type, role, and first content block.
Orients you to the transcript shape before any analysis.
```sh
jq -r '.[] | "\(.original_index) | \(.type) | \(.role) | \(if .content[0] | type == "object" then .content[0].type + " " + (.content[0].name // "") else "text" end) | \(if .content[0] | type == "object" then (.content[0].command[:80] // .content[0].path // "") else (.content[0][:80]) end)"' transcript.json
```

**Per-message block count** — some formats pack many tool calls into one message.
A message with 47 content blocks needs block-level handling, not message-level.
```sh
jq '[.[] | {idx: .original_index, blocks: (.content | length)}] | sort_by(-.blocks) | .[0:5]' transcript.json
```

**Mixed-content detection** — finds messages where Read/Write/Edit blocks share
a container with Bash or other tools. These need block-level removal, not whole-message drop.
```sh
jq '[.[] | select(any(.content[]; type == "object" and (.name == "Read" or .name == "Write" or .name == "Edit"))) | {idx: .original_index, has_other: (any(.content[]; type == "object" and (.name | IN("Read","Write","Edit") | not)))}] | map(select(.has_other)) | map(.idx)' transcript.json
```

### For workflow / verification

**Set-difference gap analysis** — after a transformation pass, compare `original_index`
sets of the before and after outputs. The delta is the exact set of indices that pass
added or removed. Useful for isolating where semantic judgment (vs. deterministic rules)
was applied.
```python
before = {m['original_index'] for m in before_data}
after  = {m['original_index'] for m in after_data}
added = sorted(after - before)
removed = sorted(before - after)
```

**"Still there" audit** — after a removal pass, check that the indices you intended
to remove are actually gone. Catches omissions in the removal logic.
```python
expected_removals = {3, 4, 8, 21, 23, ...}
actually_still_there = sorted(current_indices & expected_removals)
assert not actually_still_there, f"Missed: {actually_still_there}"
```

**Post-transform content counter** — after each pass, count remaining content types
to verify no residues (e.g., `tool-output:Read` or `todo` blocks) survived.
```python
from collections import Counter
types = Counter()
for m in data:
    for b in m.get('content', []):
        if isinstance(b, str) and b.startswith('<'):
            types['path-ref'] += 1
        elif isinstance(b, dict):
            types[f"{b.get('type','?')}:{b.get('name','?')}"] += 1
print(types.most_common())
```
